#!/bin/bash
cabal configure --distdir dist-profiling --enable-profiling --ghc-option=-rtsopts --ghc-option=-auto-all --ghc-option=-threaded --ghc-option=-fprof-auto --ghc-option="-with-rtsopts=-N -p -s -h -i0.1"
cabal build --distdir dist-profiling --ghc-option=-rtsopts --ghc-option=-auto-all --ghc-option=-threaded --ghc-option=-fprof-auto --ghc-option="-with-rtsopts=-N -p -s -h -i0.1"
